Adding List Content
geocortex/meridian-design pull request #4
Opened 2021-02-08 22:23 UTC by Woolfe-Glitch

Just Moving over the List writing, will be adding images shortly.

2021-03-08 22:15 UTC, garrettdigital commented
Selected Item section is more of a "state" than a type of list. I suggest moving this content down to the Selected/Active state section.

2021-03-08 22:15 UTC, garrettdigital commented
The various states could benefit from having screen shots included to demonstrate what they look like.

2021-03-15 20:59 UTC, garrettdigital commented on docs/design-language.md
> +When a hover state is evoked, it cannot rely on simply a colour change. There must be a stage change that shows there is a differentiation to pull them into WCAG compliance. There is typically a back
"evoked" should be "invoked".

2021-03-15 21:00 UTC, garrettdigital commented on docs/design-language.md
> +When a hover state is evoked, it cannot rely on simply a colour change. There must be a stage change that shows there is a differentiation to pull them into WCAG compliance. There is typically a back
"stage change" should be "state change"

2021-04-05 21:06 UTC, garrettdigital requested changes

2021-04-05 21:06 UTC, garrettdigital commented on docs/design-language.md
> +When a hover state is triggered, it cannot just rely on a color change. There also must be a state change that shows the differentiation. For example, in our programs, there is a background color cha
Can I suggest adding in some wording to explain why we can't just use color when hovering? Something along the lines of, "A hover state cannot rely on a color change as the only indication that it is being hovered due to users that may be colorblind or have other visual impairments. In our applications we will typically add a border along with a color change to be WCAG compliant."

2021-04-05 21:21 UTC, garrettdigital approved these changes

2021-07-12 21:13 UTC, jfgodin approved these changes

2021-07-12 21:39 UTC, garrettdigital requested changes
"States" are showing up as a top level item in the right side menu. I assume it's just an issue with the heading levels that needs to be corrected.

2021-08-09 21:40 UTC, garrettdigital approved these changes

2021-08-09 21:40 UTC, merged