Update Docusaurus to 2.3.0
geocortex/meridian-design pull request #51
Opened 2023-02-02 19:36 UTC by jfgodin

2023-02-21 22:14 UTC, garrettdigital requested changes
At some point, we've lost the borders around all of the example images. I think it was the class ".img-example" that added the borders. Might as well add them back in this PR even though I this wasn't where it was broken.

2023-02-21 23:10 UTC, jfgodin commented
> 

Fixed using a substring selector. This method is a known solution. Down the road we may want to consider Swizzling https://docusaurus.io/docs/swizzling

2023-02-21 23:29 UTC, jfgodin commented
Ignore previous comment. Going forward use className="" instead of class="" in any Markdown file.

2023-02-22 16:40 UTC, garrettdigital approved these changes

2023-02-22 16:41 UTC, merged